[versions]
spring = "4.0.1"
restAssured = "6.0.0"
mockito = "5.19.0"
assertj = "3.27.3"
archunit = "1.4.1"
axon = "5.0.3"
jsonwebtoken = "0.9.1"
jaxbApi = "2.3.1"
passay = "1.6.4"
springDependencyManagementPlugin = "1.1.7"
springDoc = "3.0.2"

[plugins]
springdependencies = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementPlugin" }
